## This notebook formats the output of CoverM genome relative abundance calculations for the heatmap.py script

#### Import all required modules

In [1]:
import pandas as pd
import os as os
import glob as glob
import numpy as np

#### Navigate to directory with CoverM outputs

In [90]:
os.chdir("/Users/nastassia.patin/GitHub/eDNA-Visualizations/MAG_relativeabundances")

##### Import sheet and truncate metagenome sample names (column names)

In [75]:
# Flyer 2018
df = pd.read_csv("Flyer2018_MAG_relabund.tsv", sep='\t')
df.columns = df.columns.str.replace("eCruises_2018-2021_MAGs_HQ_dRep_concat.fa/", 
                                  "", regex=False)
df.columns = df.columns.str.replace("R1_interleaved.fq.gz Relative Abundance (%)", 
                                  "", regex=False)
df.head(3)

,Genome,zr2760_10_,zr2760_12_,zr2760_13_,zr2760_16_,zr2760_17_,zr2760_18_,zr2760_1_,zr2760_20_,zr2760_21_,...,zr2760_82_,zr2760_83_,zr2760_88_,zr2760_8_,zr2760_90_,zr2760_91_,zr2760_92_,zr2760_93_,zr2760_94_,zr2760_95_
0,unmapped,77.307740,78.005066,55.711110,83.618675,80.537430,78.890335,55.756770,76.784480,81.635666,...,74.450810,69.768110,96.488230,85.414250,95.471640,88.988045,88.923256,84.632645,6.729066,6.578440
1,1903c117-100m-2-MaxBin2-002-Lasker2019,0.169097,0.142159,0.006856,0.046664,0.114496,0.050308,0.010401,0.169665,0.111496,...,0.002741,0.002373,0.001095,0.003362,0.002159,0.002722,0.003101,0.002820,0.009664,0.007602
2,1903c122-100m-2-MaxBin2-021-Lasker2019,0.096563,0.057928,0.000643,0.001668,0.050605,0.002475,0.000539,0.068065,0.109982,...,0.000141,0.000051,0.000014,0.000224,0.000112,0.000072,0.000272,0.000109,0.000045,0.000063

In [50]:
# Lasker 2018
df = pd.read_csv("Lasker2018_MAG_relabund.tsv", sep='\t')
df.columns = df.columns.str.replace("eCruises_2018-2021_MAGs_HQ_dRep_concat.fa/", 
                                  "", regex=False)
df.columns = df.columns.str.replace("_S[0-9]+_L002_interleaved.fq.gz ", 
                                  "", regex=True)
df.columns = df.columns.str.replace("Relative Abundance (%)", 
                                  "", regex=False)
df.head(3)

,Genome,D0052A,D0053A,D0057A,D0058A,D0063A,D0064A,D0068A,D0069A,D0073A,...,D0198A,D0203A,D0208A,D0213A,D0270A,D0271A,D0275A,D0276A,D1030A,D1031A
0,unmapped,82.246864,81.169590,62.603740,59.369860,76.486160,76.107070,78.868510,79.350980,82.565990,...,78.280810,77.897940,81.822420,67.632450,72.25406,72.406450,64.896580,68.301470,63.422607,62.230670
1,1903c117-100m-2-MaxBin2-002-Lasker2019,0.139195,0.146078,0.007739,0.007767,0.137418,0.136292,0.001154,0.001086,0.130485,...,0.166000,0.001601,0.132653,0.002486,0.10038,0.099171,0.002985,0.002556,0.019601,0.018438
2,1903c122-100m-2-MaxBin2-021-Lasker2019,0.025858,0.028847,0.000105,0.000147,0.036929,0.036015,0.000666,0.000907,0.035669,...,0.065834,0.000613,0.062787,0.000225,0.01951,0.019252,0.001442,0.001527,0.000024,0.000050

In [91]:
# Lasker 2019
df = pd.read_csv("Lasker2019_MAG_relabund.tsv", sep='\t')
df.columns = df.columns.str.replace("eCruises_2018-2021_MAGs_", 
                                  "", regex=False)
df.columns = df.columns.str.replace("-sorted Relative Abundance (%)", 
                                  "", regex=False)
df.head(3)

,Genome,1903buk1_0m-1,1903buk1_0m-2,1903buk2_0m-1,1903buk2_0m-2,1903buk3_0m-1,1903buk3_0m-2,1903buk4_0m-1,1903buk4_0m-2,1903_buk5-1,...,Las19c135_5m-1,Las19c135_5m-2,Las19c135_70m-1,Las19c135_70m-2,Las19c135_70m-3,Las19c138_100m-1,Las19c138_100m-2,Las19c138_100m-3,Las19c138_12m-1,Las19c138_27m-1
0,unmapped,100.0,89.77045,87.436295,75.653496,88.46916,90.42071,91.62734,83.45378,75.776054,...,72.53338,76.30101,73.064150,70.147600,71.644844,71.044945,71.650780,100.0,71.759285,NaN
1,1903c117-100m-2-MaxBin2-002-Lasker2019,NaN,0.00000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.176564,0.282884,0.262496,0.421002,0.404573,NaN,0.000000,NaN
2,1903c122-100m-2-MaxBin2-021-Lasker2019,NaN,0.00000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.035540,0.073857,0.076317,0.117223,0.098988,NaN,0.000000,NaN

In [105]:
# Lasker 2021
df = pd.read_csv("Lasker2021_MAG_relabund.tsv", sep='\t')
df.columns = df.columns.str.replace("eCruises_2018-2021_MAGs_HQ_dRep_concat.fa/", 
                                  "", regex=False)
df.columns = df.columns.str.replace("_interleaved.fq.gz Relative Abundance (%)", 
                                  "", regex=False)
df.head(3)

,Genome,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,RL2103c009_5m-3,...,RL2103c081_45m-2,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2
0,unmapped,62.353470,53.118470,78.239650,61.614597,56.403214,56.649853,53.854763,55.838158,50.231487,...,59.491325,54.548790,57.477350,57.788456,58.111374,50.097836,49.268310,78.003060,53.309143,52.547623
1,1903c117-100m-2-MaxBin2-002-Lasker2019,0.070716,0.010599,0.002767,0.085346,0.004342,0.003007,0.015832,0.021520,0.011754,...,0.046833,0.007559,0.013911,0.020059,0.014307,0.010262,0.008622,0.190090,0.021886,0.018418
2,1903c122-100m-2-MaxBin2-021-Lasker2019,0.015480,0.000236,0.000152,0.010897,0.000480,0.001002,0.000019,0.000366,0.000053,...,0.007452,0.000018,0.000048,0.000176,0.001598,0.000233,0.000262,0.071384,0.001695,0.001784

##### Remove the 'unmapped' row

In [106]:
df = df.iloc[1:, :]
df.head(3)

,Genome,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,RL2103c009_5m-3,...,RL2103c081_45m-2,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2
1,1903c117-100m-2-MaxBin2-002-Lasker2019,0.070716,0.010599,0.002767,0.085346,0.004342,0.003007,0.015832,0.021520,0.011754,...,0.046833,0.007559,0.013911,0.020059,0.014307,0.010262,0.008622,0.190090,0.021886,0.018418
2,1903c122-100m-2-MaxBin2-021-Lasker2019,0.015480,0.000236,0.000152,0.010897,0.000480,0.001002,0.000019,0.000366,0.000053,...,0.007452,0.000018,0.000048,0.000176,0.001598,0.000233,0.000262,0.071384,0.001695,0.001784
3,1903c122-5m-2-MaxBin2-008-Lasker2019,0.038496,0.073668,0.022466,0.038497,0.077661,0.081868,0.034803,0.033221,0.029069,...,0.025633,0.024240,0.036804,0.037963,0.017924,0.024822,0.025032,0.000218,0.029603,0.034526

##### Remove all MAGs generated from control samples (Flyer 2018)

In [107]:
controls = ['zr2760-13', 'zr2760_34', 'zr2760-8', 'zr2760-9']
df = df.drop(df[df['Genome'].str.contains('|'.join(controls))].index)
df.tail(3)

,Genome,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,RL2103c009_5m-3,...,RL2103c081_45m-2,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2
540,zr2760-64-MaxBin2-010,0.087858,0.002267,0.000793,0.086594,0.000211,0.000017,0.000729,0.003260,0.000106,...,0.035373,0.000019,0.000352,0.002758,0.007381,0.002117,0.002343,0.187706,0.011147,0.009950
541,zr2760-69-MaxBin2-012,0.090771,0.002404,0.000827,0.087293,0.000253,0.000018,0.000871,0.003687,0.000178,...,0.036180,0.000096,0.000518,0.003034,0.007569,0.002292,0.002341,0.194069,0.011472,0.010731
542,zr2760-78-MaxBin2-063,0.038627,0.078638,0.042160,0.044195,0.078411,0.060497,0.104011,0.105726,0.067974,...,0.056334,0.131778,0.080953,0.092181,0.206185,0.273832,0.268273,0.000396,0.268015,0.222312

##### Remove all control samples (Flyer 2018 only)

In [78]:
controls = ['zr2760_1_', 'zr2760_5_', 'zr2760_8_', 'zr2760_13', 'zr2760_22',
            'zr2760_34', 'zr2760_72', 'zr2760_80', 'zr2760_81', 'zr2760_82', 
            'zr2760_83', 'zr2760_88', 'zr2760_90', 'zr2760_91', 'zr2760_92', 
            'zr2760_93', 'zr2760_94', 'zr2760_95']

In [79]:
df = df.loc[:, ~df.columns.str.contains('|'.join(controls))]
df.head(3)

,Genome,zr2760_10_,zr2760_12_,zr2760_16_,zr2760_17_,zr2760_18_,zr2760_20_,zr2760_21_,zr2760_23_,zr2760_24_,...,zr2760_69_,zr2760_70_,zr2760_71_,zr2760_73_,zr2760_74_,zr2760_75_,zr2760_76_,zr2760_77_,zr2760_78_,zr2760_79_
1,1903c117-100m-2-MaxBin2-002-Lasker2019,0.169097,0.142159,0.046664,0.114496,0.050308,0.169665,0.111496,0.128073,0.137574,...,0.042905,0.018450,0.027732,0.011998,0.006441,0.035312,0.025285,0.005703,0.007013,0.040236
2,1903c122-100m-2-MaxBin2-021-Lasker2019,0.096563,0.057928,0.001668,0.050605,0.002475,0.068065,0.109982,0.042983,0.078892,...,0.002013,0.005093,0.001686,0.000566,0.000598,0.001710,0.001103,0.001321,0.000744,0.002012
3,1903c122-5m-2-MaxBin2-008-Lasker2019,0.000793,0.000544,0.020895,0.000630,0.024643,0.001768,0.001051,0.001037,0.001197,...,0.017466,0.013121,0.027921,0.042697,0.018731,0.017859,0.017494,0.013944,0.023788,0.018527

### Merge the genome taxonomy level of interest with relative abundance sheet

#### Navigate to directory containing MAG taxonomies

In [108]:
os.chdir("/Users/nastassia.patin/Desktop/Projects/eCruises_TIMESERIES/Metagenomes_2018-2021/MAG_QC/")

##### Import the MAG taxonomy sheet

In [109]:
tax = pd.read_csv("MAGs_2018-2021_HQ_dRep_quality_tax_noCs.csv")
tax.head(3)

,bin,quality,total_scgs,supporting_scgs,domain,phylum,class,order,family,genus,species,dataset,completion,redundancy,quality.1
0,1903c117_100m-2_MaxBin2_002-Lasker2019,59.21,8,5,Archaea,Thermoplasmatota,Poseidoniia,Poseidoniales,Thalassarchaeaceae,MGIIb-O1,MGIIb-O1 sp002497895,Lasker2019,92.11,6.58,59.21
1,1903c122_100m-2_MaxBin2_021-Lasker2019,56.32,15,11,Bacteria,Actinobacteriota,Acidimicrobiia,Acidimicrobiales,MedAcidi-G1,S20-B6,S20-B6 sp002699725,Lasker2019,70.42,2.82,56.32
2,1903c122_5m-2_MaxBin2_008-Lasker2019,59.14,18,9,Bacteria,Proteobacteria,Alphaproteobacteria,Puniceispirillales,Puniceispirillaceae,UBA3439,UBA3439 sp002378605,Lasker2019,73.24,2.82,59.14

In [110]:
taxon = 'phylum'
tax = tax[['bin', taxon]].rename(columns={'bin':'Genome'})
tax['Genome'] = tax['Genome'].str.replace('_', '-')
tax.head(3)

                                   Genome            phylum
0  1903c117-100m-2-MaxBin2-002-Lasker2019  Thermoplasmatota
1  1903c122-100m-2-MaxBin2-021-Lasker2019  Actinobacteriota
2    1903c122-5m-2-MaxBin2-008-Lasker2019    Proteobacteria

In [111]:
df_tax = df.merge(tax, on='Genome', how='left')
df_tax.head(3)

,Genome,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,RL2103c009_5m-3,...,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2,phylum
0,1903c117-100m-2-MaxBin2-002-Lasker2019,0.070716,0.010599,0.002767,0.085346,0.004342,0.003007,0.015832,0.021520,0.011754,...,0.007559,0.013911,0.020059,0.014307,0.010262,0.008622,0.190090,0.021886,0.018418,Thermoplasmatota
1,1903c122-100m-2-MaxBin2-021-Lasker2019,0.015480,0.000236,0.000152,0.010897,0.000480,0.001002,0.000019,0.000366,0.000053,...,0.000018,0.000048,0.000176,0.001598,0.000233,0.000262,0.071384,0.001695,0.001784,Actinobacteriota
2,1903c122-5m-2-MaxBin2-008-Lasker2019,0.038496,0.073668,0.022466,0.038497,0.077661,0.081868,0.034803,0.033221,0.029069,...,0.024240,0.036804,0.037963,0.017924,0.024822,0.025032,0.000218,0.029603,0.034526,Proteobacteria

In [112]:
# get a list of columns
cols = list(df_tax)
# move the column to head of list using index, pop and insert
cols.insert(0, cols.pop(cols.index(taxon)))
df_tax = df_tax.loc[:, cols]
df_tax.head(3)

,phylum,Genome,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,...,RL2103c081_45m-2,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2
0,Thermoplasmatota,1903c117-100m-2-MaxBin2-002-Lasker2019,0.070716,0.010599,0.002767,0.085346,0.004342,0.003007,0.015832,0.021520,...,0.046833,0.007559,0.013911,0.020059,0.014307,0.010262,0.008622,0.190090,0.021886,0.018418
1,Actinobacteriota,1903c122-100m-2-MaxBin2-021-Lasker2019,0.015480,0.000236,0.000152,0.010897,0.000480,0.001002,0.000019,0.000366,...,0.007452,0.000018,0.000048,0.000176,0.001598,0.000233,0.000262,0.071384,0.001695,0.001784
2,Proteobacteria,1903c122-5m-2-MaxBin2-008-Lasker2019,0.038496,0.073668,0.022466,0.038497,0.077661,0.081868,0.034803,0.033221,...,0.025633,0.024240,0.036804,0.037963,0.017924,0.024822,0.025032,0.000218,0.029603,0.034526

#### Remove all MAGs in the phylum Firmicutes

In [113]:
df_tax = df_tax.drop(df_tax[df_tax['phylum'].str.contains('Firmicutes')].index)
df_tax.head(3)

,phylum,Genome,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,...,RL2103c081_45m-2,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2
0,Thermoplasmatota,1903c117-100m-2-MaxBin2-002-Lasker2019,0.070716,0.010599,0.002767,0.085346,0.004342,0.003007,0.015832,0.021520,...,0.046833,0.007559,0.013911,0.020059,0.014307,0.010262,0.008622,0.190090,0.021886,0.018418
1,Actinobacteriota,1903c122-100m-2-MaxBin2-021-Lasker2019,0.015480,0.000236,0.000152,0.010897,0.000480,0.001002,0.000019,0.000366,...,0.007452,0.000018,0.000048,0.000176,0.001598,0.000233,0.000262,0.071384,0.001695,0.001784
2,Proteobacteria,1903c122-5m-2-MaxBin2-008-Lasker2019,0.038496,0.073668,0.022466,0.038497,0.077661,0.081868,0.034803,0.033221,...,0.025633,0.024240,0.036804,0.037963,0.017924,0.024822,0.025032,0.000218,0.029603,0.034526

In [114]:
df_tax = df_tax.dropna(axis='columns')

##### Export

In [115]:
os.chdir("/Users/nastassia.patin/GitHub/eDNA-Visualizations/MAG_relativeabundances")
df_tax.to_csv("Lasker2021_MAG_relabund_forheatmap-phylum.tsv", sep='\t', index=False)

#### Log-normalize and export

In [116]:
df_tax = df_tax.set_index([taxon, 'Genome'])
df_tax = df_tax + 0.000000001
df_tax = np.log(df_tax)
df_tax.head(3)

,,RL2103c001_100m-2,RL2103c001_48m-1,RL2103c001_5m-1,RL2103c002_100m-1,RL2103c002_48m-3,RL2103c002_5m-1,RL2103c009_20m-1,RL2103c009_40m-1,RL2103c009_5m-3,RL2103c010_25m-3,...,RL2103c081_45m-2,RL2103c081_5m-2,RL2103c088_51m-2,RL2103c088_5m-1,RL2103c089_100m-3,RL2103c089_20m-1,RL2103c089_5m-2,RL2103c090_100m-3,RL2103c090_53m-1,RL2103c090_5m-2
phylum,Genome,,,,,,,,,,,,,,,,,,,,,
Thermoplasmatota,1903c117-100m-2-MaxBin2-002-Lasker2019,-2.649079,-4.546999,-5.890000,-2.461042,-5.439377,-5.806816,-4.145710,-3.838750,-4.443561,-4.139667,...,-3.061175,-4.885052,-4.275062,-3.909068,-4.246973,-4.579339,-4.753381,-1.660260,-3.821900,-3.994417
Actinobacteriota,1903c122-100m-2-MaxBin2-021-Lasker2019,-4.168223,-8.350556,-8.793957,-4.519225,-7.641270,-6.905473,-10.878302,-7.912723,-9.846331,-8.043569,...,-4.899254,-10.920947,-9.946756,-8.644191,-6.439160,-8.363040,-8.245532,-2.639676,-6.380278,-6.329041
Proteobacteria,1903c122-5m-2-MaxBin2-008-Lasker2019,-3.257191,-2.608190,-3.795769,-3.257185,-2.555406,-2.502645,-3.358066,-3.404577,-3.538090,-3.396022,...,-3.663866,-3.719764,-3.302145,-3.271145,-4.021604,-3.696007,-3.687591,-8.433208,-3.519876,-3.366038

In [117]:
df_tax.to_csv("Lasker2021_MAG_relabund_log_forheatmap-phylum.tsv", 
              sep='\t', index=True)